### ISSUE TITLE
Doubt regarding the model of the  raspberry pi  board

### ISSUE THREAD

**Issue by codeit6996** [GianlucaPaolocci/Sound-classification-on-Raspberry-Pi-with-Tensorflow#15]
Is this supportive for all models of raspberry pi or a specific one ? if specific do tell which one. Needed it urgently

**Comment by GianlucaPaolocci** [comment]
You can use any model of raspberry, I suggest you Pi2 or above for performance.

**Comment by codeit6996** [comment]
Thank you for your email, will contact you for further doubts.
